# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0.xci
# IP: The module: 'design_1_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/bd_e547.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547 || ORIG_REF_NAME==bd_e547} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_e547_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_microblaze_I_0 || ORIG_REF_NAME==bd_e547_microblaze_I_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_e547_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_rst_0_0 || ORIG_REF_NAME==bd_e547_rst_0_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_e547_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_ilmb_0 || ORIG_REF_NAME==bd_e547_ilmb_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_e547_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_dlmb_0 || ORIG_REF_NAME==bd_e547_dlmb_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_e547_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_dlmb_cntlr_0 || ORIG_REF_NAME==bd_e547_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_e547_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_ilmb_cntlr_0 || ORIG_REF_NAME==bd_e547_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_e547_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_lmb_bram_I_0 || ORIG_REF_NAME==bd_e547_lmb_bram_I_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_e547_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_iomodule_0_0 || ORIG_REF_NAME==bd_e547_iomodule_0_0} -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_e547_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_microblaze_I_0 || ORIG_REF_NAME==bd_e547_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_e547_microblaze_I_0_ooc_debug.xdc

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_e547_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_rst_0_0 || ORIG_REF_NAME==bd_e547_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_e547_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_rst_0_0 || ORIG_REF_NAME==bd_e547_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_e547_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_ilmb_0 || ORIG_REF_NAME==bd_e547_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_e547_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_dlmb_0 || ORIG_REF_NAME==bd_e547_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_e547_lmb_bram_I_0_ooc.xdc

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_e547_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_iomodule_0_0 || ORIG_REF_NAME==bd_e547_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/bd_e547_ooc.xdc

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0.xci
# IP: The module: 'design_1_microblaze_mcs_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/bd_e547.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547 || ORIG_REF_NAME==bd_e547} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_e547_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_microblaze_I_0 || ORIG_REF_NAME==bd_e547_microblaze_I_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_e547_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_rst_0_0 || ORIG_REF_NAME==bd_e547_rst_0_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_e547_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_ilmb_0 || ORIG_REF_NAME==bd_e547_ilmb_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_e547_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_dlmb_0 || ORIG_REF_NAME==bd_e547_dlmb_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_e547_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_dlmb_cntlr_0 || ORIG_REF_NAME==bd_e547_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_e547_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_ilmb_cntlr_0 || ORIG_REF_NAME==bd_e547_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_e547_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_lmb_bram_I_0 || ORIG_REF_NAME==bd_e547_lmb_bram_I_0} -quiet] -quiet

# IP: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_e547_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e547_iomodule_0_0 || ORIG_REF_NAME==bd_e547_iomodule_0_0} -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_e547_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_microblaze_I_0 || ORIG_REF_NAME==bd_e547_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_e547_microblaze_I_0_ooc_debug.xdc

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_e547_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_rst_0_0 || ORIG_REF_NAME==bd_e547_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_e547_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_rst_0_0 || ORIG_REF_NAME==bd_e547_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_e547_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_ilmb_0 || ORIG_REF_NAME==bd_e547_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_e547_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_dlmb_0 || ORIG_REF_NAME==bd_e547_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_e547_lmb_bram_I_0_ooc.xdc

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_e547_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e547_iomodule_0_0 || ORIG_REF_NAME==bd_e547_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/bd_0/bd_e547_ooc.xdc

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/peter/PicoEVB/20191/project_1.srcs/sources_1/bd/design_1/ip/design_1_microblaze_mcs_0_0/design_1_microblaze_mcs_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_microblaze_mcs_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
